"""Remove table niveau_qualification

Revision ID: 07a7a6cd02de
Revises: 08758dcf9b06
Create Date: 2025-07-15 19:47:14.379503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07a7a6cd02de'
down_revision = '08758dcf9b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('niveau_qualification')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('niveau_qualification',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('niveau', sa.VARCHAR(length=100), nullable=True),
    sa.Column('categorie', sa.VARCHAR(length=100), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
