"""Add table modele_ardoises

Revision ID: 08758dcf9b06
Revises: 4beffe21d4f3
Create Date: 2025-07-15 19:20:27.794582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08758dcf9b06'
down_revision = '4beffe21d4f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modele_ardoises',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('modele_ardoises', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_audit_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prix', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_audit_table')
    op.drop_table('modele_ardoises')
    # ### end Alembic commands ###
