"""Add salaries table

Revision ID: 67c7312c6bf7
Revises: e189113ea343
Create Date: 2025-07-19 09:55:45.341385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67c7312c6bf7'
down_revision = 'e189113ea343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nom', sa.String(length=30), nullable=True),
    sa.Column('prenom', sa.String(length=30), nullable=True),
    sa.Column('salaire_brut_horaire', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nbre_heure_hebdo', sa.Float(), nullable=True),
    sa.Column('date_entree', sa.Date(), nullable=True),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('niveau_qualification_id', sa.Integer(), nullable=True),
    sa.Column('colonne_planning', sa.Integer(), nullable=True),
    sa.Column('famille_ouvrages', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('adresse', sa.String(length=100), nullable=True),
    sa.Column('code_postal', sa.Integer(), nullable=True),
    sa.Column('ville', sa.String(length=100), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('num_securite_social', sa.Integer(), nullable=True),
    sa.Column('num_telephone', sa.String(length=30), nullable=True),
    sa.Column('ondrive_path', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['adresse'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['code_postal'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['colonne_planning'], ['niveau_qualification.id'], ),
    sa.ForeignKeyConstraint(['date_naissance'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['email'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['famille_ouvrages'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['num_securite_social'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['num_telephone'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['ondrive_path'], ['famille_ouvrages.id'], ),
    sa.ForeignKeyConstraint(['ville'], ['famille_ouvrages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salaries')
    # ### end Alembic commands ###
