"""Fix clients table and add ville_id foreign key

Revision ID: 74970c218c28
Revises: bd46955e15f8
Create Date: 2025-07-21 21:15:32.301917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74970c218c28'
down_revision = 'bd46955e15f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ville', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ville_id', sa.Integer(), nullable=True))
        batch_op.alter_column('nom',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('prenom',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('num_telephone',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('adresse',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('code_postal',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('siret',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=14),
               existing_nullable=True)
        batch_op.create_foreign_key('fk_clients_ville', 'villes', ['ville_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('villes')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('villes', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint('fk_clients_ville', type_='foreignkey')
        batch_op.alter_column('siret',
               existing_type=sa.String(length=14),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('code_postal',
               existing_type=sa.String(length=10),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('adresse',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('num_telephone',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('prenom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.alter_column('nom',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_column('ville_id')
        batch_op.drop_column('ville')

    # ### end Alembic commands ###
