"""Remove duplicate ville column and fix ville_id relation

Revision ID: 876812c29caf
Revises: 74970c218c28
Create Date: 2025-07-21 21:27:40.640113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '876812c29caf'
down_revision = '74970c218c28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_column('ville')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ville', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
