"""Module 2 - Automatisation tâches

Revision ID: 8b1ef94d7631
Revises: 7933e5172404
Create Date: 2025-07-22 18:59:30.644537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b1ef94d7631'
down_revision = '7933e5172404'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('famille_tach',
    sa.Column('famille_tache', sa.String(length=50), nullable=False),
    sa.Column('type_tache', sa.String(length=100), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('auto_generee', sa.Boolean(), nullable=True),
    sa.Column('declencheur', sa.String(length=50), nullable=True),
    sa.Column('mot_cle_famille_ouvrage', sa.String(length=100), nullable=True),
    sa.Column('famille_ouvrage_id', sa.Integer(), nullable=True),
    sa.Column('montant_seuil', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('statut_defaut', sa.String(length=30), nullable=True),
    sa.Column('priorite_defaut', sa.String(length=20), nullable=True),
    sa.Column('delai_jours', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['famille_ouvrage_id'], ['famille_ouvrages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chantiers',
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('contact_principal', sa.String(length=100), nullable=True),
    sa.Column('date_creation', sa.Date(), nullable=True),
    sa.Column('date_signature', sa.Date(), nullable=True),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('statut', sa.String(length=30), nullable=True),
    sa.Column('montant_ht', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('montant_ttc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('taches_reelles',
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('utilisateur', sa.String(length=50), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=True),
    sa.Column('priorite', sa.String(length=10), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_echeance', sa.DateTime(), nullable=True),
    sa.Column('date_completion', sa.DateTime(), nullable=True),
    sa.Column('temps_estime', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('temps_passe', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_generee', sa.Boolean(), nullable=True),
    sa.Column('declencheur', sa.String(length=50), nullable=True),
    sa.Column('famille_tach_id', sa.Integer(), nullable=True),
    sa.Column('chantier_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chantier_id'], ['chantiers.id'], ),
    sa.ForeignKeyConstraint(['famille_tach_id'], ['famille_tach.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('taches_reelles')
    op.drop_table('chantiers')
    op.drop_table('famille_tach')
    # ### end Alembic commands ###
