"""Add clients table

Revision ID: bd46955e15f8
Revises: ced7cb0247ee
Create Date: 2025-07-21 20:48:31.587119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd46955e15f8'
down_revision = 'ced7cb0247ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('civilite', sa.Enum(), nullable=True),
    sa.Column('nom', sa.String(length=50), nullable=True),
    sa.Column('prenom', sa.String(length=50), nullable=True),
    sa.Column('adresse', sa.String(length=50), nullable=True),
    sa.Column('code_postal', sa.Integer(), nullable=True),
    sa.Column('villes', sa.Integer(), nullable=True),
    sa.Column('num_telephone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('siret', sa.Integer(), nullable=True),
    sa.Column('id_contact_google', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clients')
    # ### end Alembic commands ###
